osx_image: xcode11.4
language: objective-c
before_install:
  - set -o pipefail
  - xcrun simctl boot "iPhone 11" || echo "(Pre)Launched the simulator."
script:
  - travis_retry xcodebuild -project Down.xcodeproj -scheme "Down" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.0,name=iPhone 11" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES test
  - travis_retry xcodebuild -project Down.xcodeproj -scheme "Down" -sdk macosx -destination 'platform=OS X,arch=x86_64' -enableCodeCoverage YES test
  - travis_retry xcodebuild -project Down.xcodeproj -scheme "Down" -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV' -enableCodeCoverage YES test
  - travis_retry xcodebuild -project Down.xcodeproj -scheme "DownSnapshotTests" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.0,name=iPhone 11" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES test
after_success:
  - bash <(curl -s https://codecov.io/bash)
